# Generated by Django 6.0.6 on 2026-07-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Vazifa nomi')),
                ('description', models.TextField(blank=True, verbose_name='Batafsil')),
                ('completed', models.BooleanField(default=False, verbose_name='Bajarildimi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
